### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ialbert** [ftwkoopmans/goat#2] opened 2023-12-12 18:24 UTC
`remotes::install_github("ftwkoopmans/goat")`

produces

```
Downloading GitHub repo ftwkoopmans/goat@HEAD
Error: Failed to install 'goat' from GitHub:
  Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' ls-remote https://git.bioconductor.org/packages/GO.db RELEASE_3_18 2>/dev/null' had status 128
```

the git remote URL does not appear to be a valid repository

**Comment by ftwkoopmans** [comment] 2023-12-12 18:38
Thanks for reporting, it seems like there is some issue with Bioconductor; 
visit https://git.bioconductor.org/packages/GO.db via a browser and you'll see the same error as reported via the R package (same with https://git.bioconductor.org ). In the GOAT R package we have some convenience functions for loading GO genesets via Bioconductor and it seems your installation halted at the point where the Bioconductor packages are being installed.

Prior to running above command to install the GOAT R package, could you first try to install the bioconductor stuff as suggested in the quickstart example (in this GitHub repo's README)?

1. `install.packages(c("BiocManager", "remotes", "pheatmap", "ggplot2"))`
2. `BiocManager::install(c("AnnotationDbi", "GO.db", "org.Hs.eg.db"))`

If either of these steps fail, please let me know what operating system and versions for R and RStudio you are using. If both steps succeed, you should be able to install the GOAT R package (because it doesn't have to do the Bioconductor installation stuff anymore)

**Comment by ialbert** [comment] 2023-12-12 18:49
I ran those but in a script and looks like it does not complete properly

BiocManager::install(c("AnnotationDbi", "GO.db", "org.Hs.eg.db"))

there is a failure along the way

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘htmltools’ 0.5.6.1 is being loaded, but >= 0.5.7 is required
  
  I will look into this closer and report back

**Comment by ialbert** [comment] 2023-12-12 18:58
I tested out in a brand new version of R, was time to update R to 4.3.2

the first install command completes fine

    BiocManager::install(c("AnnotationDbi", "GO.db", "org.Hs.eg.db"))

I get 

    * DONE (GO.db)
    * DONE (org.Hs.eg.db)

but then the next command

    remotes::install_github("ftwkoopmans/goat")

fails with:

```
Downloading GitHub repo ftwkoopmans/goat@HEAD
Error: Failed to install 'goat' from GitHub:
  Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' ls-remote https://git.bioconductor.org/packages/GO.db RELEASE_3_18 2>/dev/null' had status 128

```

**Comment by ialbert** [comment] 2023-12-12 19:02
A related comment: I think when a resource does not have the right annotations, the library should stop and print a meaningful message, rather than going out onto hardcoded URLS with git. That it is brittle approach (as seen here) because it depends on things out of one's control.

**Comment by ftwkoopmans** [comment] 2023-12-12 20:46
Thanks for investigating! 

The issue seems to be that the `remotes` R package (and `devtools` alike) insist on checking up on Bioconductor R package dependencies via git.bioconductor.org , which fails because git.bioconductor.org is down. So the problem is not with R code implemented in the GOAT package but with R package installation tooling/infrastructure (that stumbles when installing dependencies of the GOAT R package). 

> A related comment: I think when a resource does not have the right annotations, the library should stop and print a meaningful message, rather than going out onto hardcoded URLS with git. That it is brittle approach (as seen here) because it depends on things out of one's control.

I agree, but as mentioned the errors you encountered (and links to git repos that are down) are triggered by the remotes/devtools codebase, which is out of my control. So I'm looking at alternative tools to help install the GOAT R package and workaround this issue.

Possibly we can resolve this by using a different toolset for the installation of the R package and its dependencies. I've tested this with a clean install but also after selectively removing 1 or multiple dependencies. So far so good !
(all tests on Windows10 though, don't have a MacBook or Linux system at hand for further testing atm) 

Please try the following and let me know if this works for you (and what OS you are using);
```
install.packages("pak") # first, install the package manager that we'll use to install GOAT in the next step
pak::pkg_install("ftwkoopmans/goat", upgrade = FALSE) # latter parameter makes us skip optional updates
```

**Comment by ialbert** [comment] 2023-12-13 15:28
Alas it still does not work, first it failed with an error of no rstudioapi, but after installing that I get another error

```
> install.packages("rstudioapi")
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/rstudioapi_0.15.0.tgz'
Content type 'application/x-gzip' length 299492 bytes (292 KB)
==================================================
downloaded 292 KB


The downloaded binary packages are in
	/var/folders/wh/1w2hjgss0yv077mk9rfdkpvm0000gn/T//RtmptwAvAm/downloaded_packages
	
> pak::pkg_install("ftwkoopmans/goat", upgrade = FALSE)
                                                                             
→ Will install 1 package.
→ Will download 1 package with unknown size.
+ goat   0.9.0 👷🏼🔧 ⬇ (GitHub: 0d6d9ba)
ℹ Getting 1 pkg with unknown size
✔ Cached copy of goat 0.9.0 (source) is the latest build 
✔ No downloads needed, all packages are cached                      
ℹ Building goat 0.9.0
✖ Failed to build goat 0.9.0                                    
Error:                                                          
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package goat.
Type .Last.error to see the more details.
> .Last.error
<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package goat.
---
Backtrace:
1. pak::pkg_install("ftwkoopmans/goat", upgrade = FALSE)
2. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
3. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("pkg_install_do_plan", asNamespace("pak"))(...)
 3. proposal$install()
 4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
 5. base::withCallingHandlers({ …
 6. pkgdepends:::handle_events(state, events)
 7. pkgdepends:::handle_event(state, i)
 8. pkgdepends:::stop_task(state, worker)
 9. pkgdepends:::stop_task_build(state, worker)
10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
11. | base::signalCondition(cond)
12. global (function (e) …
```

**Comment by ialbert** [comment] 2023-12-13 15:29
I have also tried to install with the original command, hoping that perhaps the previous error was transitory, I do get pretty far now but still fails, this time with a Fortran compilation error

```
> remotes::install_github("ftwkoopmans/goat")
Downloading GitHub repo ftwkoopmans/goat@HEAD
Installing 5 packages: RcppArmadillo, RcppEigen, prettyunits, hms, progress
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/RcppArmadillo_0.12.6.6.1.tgz'
Content type 'application/x-gzip' length 1695135 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/RcppEigen_0.3.3.9.4.tgz'
Content type 'application/x-gzip' length 4489665 bytes (4.3 MB)
==================================================
downloaded 4.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/prettyunits_1.2.0.tgz'
Content type 'application/x-gzip' length 155804 bytes (152 KB)
==================================================
downloaded 152 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/hms_1.1.3.tgz'
Content type 'application/x-gzip' length 99181 bytes (96 KB)
==================================================
downloaded 96 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/progress_1.2.3.tgz'
Content type 'application/x-gzip' length 85187 bytes (83 KB)
==================================================
downloaded 83 KB


The downloaded binary packages are in
	/var/folders/wh/1w2hjgss0yv077mk9rfdkpvm0000gn/T//RtmptwAvAm/downloaded_packages
Running `R CMD build`...
* checking for file ‘/private/var/folders/wh/1w2hjgss0yv077mk9rfdkpvm0000gn/T/RtmptwAvAm/remotesb7091a2759ee/ftwkoopmans-goat-0d6d9ba/DESCRIPTION’ ... OK
* preparing ‘goat’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘goat_0.9.0.tar.gz’
* installing *source* package ‘goat’ ...
** using staged installation
** libs
using C++ compiler: ‘Apple clang version 14.0.0 (clang-1400.0.29.202)’
using C++14
using SDK: ‘MacOSX13.1.sdk’
clang++ -arch x86_64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch x86_64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c rcpp_gene_to_geneset_scores.cpp -o rcpp_gene_to_geneset_scores.o
clang++ -arch x86_64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c rcpp_null_distributions.cpp -o rcpp_null_distributions.o
clang++ -arch x86_64 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/x86_64/lib -o goat.so RcppExports.o rcpp_gene_to_geneset_scores.o rcpp_null_distributions.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0'
ld: warning: directory not found for option '-L/opt/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [goat.so] Error 1
ERROR: compilation failed for package ‘goat’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/goat’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wh/1w2hjgss0yv077mk9rfdkpvm0000gn/T//RtmptwAvAm/fileb70969fb770c/goat_0.9.0.tar.gz’ had non-zero exit status
```

**Comment by ialbert** [comment] 2023-12-13 16:07
Ok I figured out the installation requirements on a Mac. First one needs to install the Fortran compiler from:

https://mac.r-project.org/tools/

I used the packaged installer from that page. Then, when using RStudio one would also need

    install.packages("rstudioapi")

with these two additions, I was able to install using the new instructions with `pak`

**Comment by ftwkoopmans** [comment] 2023-12-13 16:10
ok great! I just landed on https://mac.r-project.org/tools/ as well after searching for the errors in your log. 

Please let me know how it goes, I'll add your MacOS tips to the installation documentation

**Comment by ialbert** [comment] 2023-12-13 16:16
I was able to run the examples on both an Intel based Mac and on a M1 based mac, 

one more suggestion is to take out the absolute paths "C:\tmp" from the examples,

so that one can run the example with no edits, most system would not have those folders anyhow

make it is write to the current directory whatever that is and plot can just pop, people know how to set these

**Comment by ftwkoopmans** [comment] 2023-12-13 17:41
Excellent! I'm currently testing on Ubuntu and Fedora. Afterwards I will update the installation instructions and examples based on your feedback.

**Closed as completed** 2023-12-15 01:14 UTC
